add test_sshd
osbuild/cloud-image-val pull request #29
Opened 2022-05-13 12:47 UTC by jabia99

ami-val tests that the instance uses systemctl. As cloud-image-val does not support rhel-6 or lower, this is not necessary.

2022-05-17 13:03 UTC, narmaku requested changes

2022-05-17 13:03 UTC, narmaku commented on test_suite/generic/test_generic.py
> +               not host.file('/etc/ssh/sshd_config').contains('#PasswordAuthentication yes'):
We could be pickier in this test.

Check what is being done here:
https://github.com/osbuild/cloud-image-val/blob/4944549b6a824d32c2e4e992f03b7e096df2422d/test_suite/cloud/test_aws.py#L220

2022-05-18 08:34 UTC, narmaku requested changes

2022-05-18 08:34 UTC, narmaku commented on test_suite/generic/test_generic.py
> +            if not re.match(pwdAuthNo, sshd_config_string) and \
Actually, how the code is done now, then we will have a false positive in the case the following line is present:
`PasswordAuthentication yes`

I think we can replace the `if` by an `assert` to follow what is being done in the other tests. In that case, the condition statements become "positive" and you avoid negations.

```
assert (re.match(pwdAuthNo, sshd_config_string) and 
    not re.match(pwdAuthYes, sshd_config_string)) or \
    re.match(f'#[ ]?{pwdAuthYes}|#[ ]+{pwdAuthYes}', sshd_config_string), \
    'Password authentication should be disabled'
```

2022-05-18 10:47 UTC, narmaku commented on test_suite/generic/test_generic.py
> +import re
```suggestion
```

2022-05-18 10:48 UTC, narmaku approved these changes
LGTM. We just need to remove the `import re` line.

2022-05-18 10:48 UTC, narmaku approved these changes

2022-05-18 10:55 UTC, jabia99 commented
Thanks for helping in this incredibly short but incredibly time consuming test!

2022-05-18 10:55 UTC, merged